#name: Get Citation Data
#
#on:
# page_build:
# schedule:
#  - cron:  '0 0 * * *'
# workflow_dispatch:
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Reqs
#      run: |
#        sudo apt-get install python3-setuptools
#    - name: Run
#      run: |
#        cd ./google_scholar_crawler
#        pip3 install -r requirements.txt
#        python3 main.py
#        cd ./results
#        git init
#        git config --local user.name "${GITHUB_ACTOR}"
#        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
#        git add *.json
#        git commit -m "Updated Citation Data"
#        git push "${remote_repo}" HEAD:google-scholar-stats --force
#      env:
#        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}

name: Get Citation Data

on:
  page_build:
  schedule:
    - cron:  '0 0 * * *'  # Trigger every day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Reqs
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools
        pip3 install -r ./google_scholar_crawler/requirements.txt

    - name: Check GOOGLE_SCHOLAR_ID
      run: |
        echo "GOOGLE_SCHOLAR_ID is: $GOOGLE_SCHOLAR_ID"

    - name: Run
      run: |
        cd ./google_scholar_crawler
        python3 main.py || { echo "Error in main.py execution"; exit 1; }

    - name: Commit and Push Data
      run: |
        cd ./google_scholar_crawler/results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "actions@github.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats
